### ISSUE TITLE
Automatically add timestamps to update() queries

### ISSUE THREAD

**Issue by hazeledmands** [goodeggs/goodeggs-mongoose-timestamps#3]
`goodeggs-mongoose-timestamps` only adds timestamps on `document.save()` calls, you have to remember to manually add `updatedAt` to `Model.update()` queries. Modules like [`mongoose-timestamp`](https://github.com/drudge/mongoose-timestamp/blob/master/index.js#L60-L84) automatically add timestamps to any mongo write operation. Perhaps we should port this functionality over?

/cc @serhalp this may explain confusion you and I were having earlier about this; turns out our newer apps are all using `mongoose-timestamp`.

**Comment by serhalp** [comment]
Whoa, `goodeggs-mongoose-timestamps` is a real thing. I thought you were just misremembering the name! ❗

**Comment by serhalp** [comment]
For the record, kale is using `mongoose-timestamp` too (albeit an old version that doesn't support `update`s either – discussed [here](https://github.com/goodeggs/goodeggs-dwh-etl/pull/128#issuecomment-228576634)).

**Comment by jhob** [comment]
For the record, `mongoose-timestamp` and the `schema.pre 'update'` behavior (for bulk updates) that it uses isn't supported until `mongoose@4.0.0`, which is a bummer for `garbanzo`.

**Comment by jhob** [comment]
With #4, I've updated `goodeggs-mongoose-timestamps` to update a model's `updatedAt` timestamp upon `model.update` calls. However this does come into effect with bulk updates via `Model.update`.

**Comment by serhalp** [comment]
Closed long ago by #4 and then even further by #5.
